module.exports = {
    STORMPATH_CLIENT_APIKEY_ID: "7GK5DMPURMO4D5CF9OBJFFA70",
    STORMPATH_CLIENT_APIKEY_SECRET: "xbj2uIVCFuD18/8u8Ps0DjlOMNySTJjsSOFaQsSLvTI",
    STORMPATH_APPLICATION_HREF: "https://api.stormpath.com/v1/applications/4RjFB6Gw9a6TqTV9pW6MAO",
    STRIPE_KEY: "sk_test_ovommL1Bi3KiBlQpCxUWJSc9"
}

/*process.env.STORMPATH_CLIENT_APIKEY_ID = "7GK5DMPURMO4D5CF9OBJFFA70";
 process.env.STORMPATH_CLIENT_APIKEY_SECRET = "xbj2uIVCFuD18/8u8Ps0DjlOMNySTJjsSOFaQsSLvTI";
 process.env.STORMPATH_APPLICATION_HREF  = "https://api.stormpath.com/v1/applications/4RjFB6Gw9a6TqTV9pW6MAO";*/