// Configuration file for authentication services
// Use environment variables or provide your own credentials

module.exports = {
    STORMPATH_CLIENT_APIKEY_ID: process.env.STORMPATH_CLIENT_APIKEY_ID || "YOUR_STORMPATH_CLIENT_APIKEY_ID",
    STORMPATH_CLIENT_APIKEY_SECRET: process.env.STORMPATH_CLIENT_APIKEY_SECRET || "YOUR_STORMPATH_CLIENT_APIKEY_SECRET",
    STORMPATH_APPLICATION_HREF: process.env.STORMPATH_APPLICATION_HREF || "YOUR_STORMPATH_APPLICATION_HREF",
    STRIPE_KEY: process.env.STRIPE_KEY || "YOUR_STRIPE_KEY"
}